# Generated by Django 5.2.8 on 2025-11-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="Широта місця проведення (наприклад, 50.4501)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="Довгота місця проведення (наприклад, 30.5234)",
                null=True,
            ),
        ),
    ]
