# Generated by Django 5.2.8 on 2025-12-03 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0009_review_image_alter_event_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("event_updated", "Подію оновлено"),
                            ("event_cancelled", "Подію скасовано"),
                            ("event_time_changed", "Час події змінено"),
                            ("event_location_changed", "Локацію змінено"),
                        ],
                        default="event_updated",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(help_text="Текст сповіщення")),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Чи прочитане сповіщення"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Подія, про яку сповіщення",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Користувач, який отримує сповіщення",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_427e4b_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="notificatio_created_ae6ed6_idx"
                    ),
                ],
            },
        ),
    ]
