# Generated by Django 5.2.8 on 2026-02-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("event_updated", "Подію оновлено"),
                    ("event_cancelled", "Подію скасовано"),
                    ("event_time_changed", "Час події змінено"),
                    ("event_location_changed", "Локацію змінено"),
                    ("rsvp_confirmed", "Нова реєстрація"),
                    ("rsvp_cancelled", "Реєстрацію скасовано"),
                ],
                default="event_updated",
                max_length=50,
            ),
        ),
    ]
